=== The `base` plugin

==== Tasks dependencies

[plantuml,base-plugin-tasks-dependencies,png]
----
@startdot
digraph D {
    node [shape=record fontname=Arial];

    clean
    check
    assemble
    build -> {check, assemble}

}
@enddot
----

==== Tasks description

* *clean*: deletes the `build` directory
** with the build cache active, `./gradlew clean build` is not enough for a clean build, you need `./gradlew --no-build-cache clean build`.
*** create a simple java app and show using `./gradlew --console=plain clean build` twice - the second time it should be `FROM-CACHE`
*** retry with `./gradlew --console=plain --no-build-cache clean build`
* *check* _lifecycle task_: plugins will add verification tasks with `tasks.check.dependsOn(myVerificationTask)`
** examples: `tasks.check.dependsOn(test)`, `tasks.check.dependsOn(pmd)`, `tasks.check.dependsOn(checkstyle)`
* *assemble* _lifecycle task_: plugins will add tasks that produce artifacts (jar, tar.gz, etc.) with `tasks.assemble.dependsOn(myArtifactProducingTask)`
** examples: `tasks.assemble.dependsOn(jar)`
