== Tasks dependencies

* tell: we could use `doFirst`/`doLast` to attach actions before/after an existing task (e.g. java compilation)
* but it's better to create a separate task and setup task dependencies
* revert changes to `settings.gradle.kts`
+
.settings.gradle.kts
[source, kotlin]
----
rootProject.name = "sample-lifecycle"
----
* tasks with dependencies
+
.build.gradle.kts
[source, kotlin]
----
tasks.register("hello") {
    group = "FedEx"
    doLast {
        println("Hi there!")
    }
}

val pourHotWaterTask = tasks.register("pourWater") {
    group = "Tea"
    doLast {
        println("pouring hot water in a mug")
    }
}

val addTeaBagsTask = tasks.register("addTeaBags") {
    group = "Tea"
    dependsOn(pourHotWaterTask)

    doLast {
        println("adding tea bags")
    }
}

val addHoneyTask = tasks.register("addHoney") {
    group = "Tea"
    dependsOn(pourHotWaterTask)

    doLast {
        println("adding honey")
    }
}

val makeTeaTask = tasks.register("makeTea") {
    group = "Tea"
    dependsOn(addTeaBagsTask)
    dependsOn(addHoneyTask)

    doLast {
        println("making tea")
    }
}


----
* `./gradlew tasks`
* `./gradlew makeTea`
* review build phases
* tell: after the configuration phase we have a DAG (directed acyclic graph) of tasks
+
[plantuml,hello-tasks-dependencies,png]
----
@startdot
digraph D {
    node [shape=record fontname=Arial];

    makeTea -> addTeaBags
    makeTea -> addHoney
    addTeaBags -> pourHotWater
    addHoney -> pourHotWater
    hello
}
@enddot
----
* tell: in the execution phase
** first we determine what tasks to execute
** then we execute the tasks and their dependencies, in the proper order
* global config to see tasks DAG as a tree
+
.~/.gradle/init.d/task-info.init.gradle.kts
[source, kotlin]
----
import org.barfuin.gradle.taskinfo.GradleTaskInfoPlugin

initscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.barfuin.gradle.taskinfo:gradle-taskinfo:2.0.0")
    }
}

allprojects {
    apply<GradleTaskInfoPlugin>()
}
----
* `./gradlew tiTree hello`
* `./gradlew tiTree makeTea`

* note: keep builds declarative, by moving custom logic in custom plugins

* note: `makeTea` doesn't do actual "work". It's there to group other tasks by depending on them. Gradle calls such tasks "lifecycle tasks".

=== Final tips

==== Tasks inputs & outputs / caching

* most tasks have inputs and outputs. For example, the `JavaCompile` task has:
** inputs
*** task configuration (e.g. command-line arguments for `javac`)
*** `.java` files to compile
** outputs
*** `.class` files
* when creating custom tasks, it's important to declare the inputs and outputs, so that Gradle can do proper caching (e.g. no point to re-run a task if its inputs didn't change)
